Dev 32 delete endpoints
dhbw-ka-pm/DnD-evolved pull request #25
Opened 2023-07-05 07:46 UTC by Umbranecis

2023-07-05 11:02 UTC, Shiny1708 commented on backend/persistence/xmlDocs/files/events/dcd374e2-a1b7-40c1-946f-c02b843a70bf.xml
Wenn das keine gewollten Demo Daten sind bitte keine xml files mitpushen

2023-07-05 11:05 UTC, Shiny1708 commented on backend/src/main/java/io/swagger/model/Event.java
sicher dass wir die Location nicht im Event haben wollen?

2023-07-05 11:06 UTC, Shiny1708 commented on backend/src/main/java/io/swagger/model/MapListWrapper.java
kann hier nicht direkt die map mit dem data handler objekt befüllt werden als teil der init() methode?

2023-07-05 11:07 UTC, Shiny1708 commented on backend/src/main/java/io/swagger/model/PatchDTOs/PatchMap.kt
warum hier nur json annotations und keine xml?

2023-07-05 11:08 UTC, Shiny1708 commented on backend/src/main/java/io/swagger/persistance/DataHandler.java
> +        return List.copyOf(maps.values());
warum übergeben wir hier eine kopie und nicht das originalobjekt?

2023-07-05 11:09 UTC, Shiny1708 requested changes
Bitte Kommentare lesen und dann bei mir melden

2023-07-12 06:44 UTC, dolerich-hirnfiedler approved these changes
supi

2023-07-12 09:39 UTC, Shiny1708 approved these changes
Hab ewig den knopf nicht gefunden am handy

2023-07-12 09:40 UTC, merged